name:  Teste de aplicacao

on:
  push:
    branches: [ main ]


    


jobs:

  unit_testing:
    name: Unitary Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

         
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        working-directory: api
        run: |
          pip install -r requirements.txt


      - name: Run Unitary Tests
        working-directory: api
        env:
          APP_ENV: test
        run: |
          pytest


security_pip:
    name: Security pip
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yaml